# sample page-view settings
page-view:
  service_account_email:    
  key_file: privatekey.p12  # service account private key file
  key_secret: notasecret    # service account private key's password
  profileID:                #ga:XXXXXXXX
  start: 3 years ago        # Beginning of report
  end: now                  # End of report
  metric: ga:pageviews      # Metric code
  segment: gaid::-1         # all visits
  filters:                  # optional
